[package]
name = "ccp-msr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-utils = {workspace = true}
thiserror = { workspace = true }
nix = { version = "0.27.1" , features = ["uio"] }
once_cell = "1.19.0"
raw-cpuid = "11.0.1"
tracing.workspace = true
