[package]
name = "ccp-main"
version = "0.1.0"
edition = "2021"

[dependencies]
capacity-commitment-prover = { version = "0.1.0", path = "../ccp" }
ccp-rpc-server = { version = "0.1.0", path = "../crates/rpc-server" }
randomx-rust-wrapper = { workspace = true }

clap = { version = "4.5.0", features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
eyre = "0.6.12"
ccp-config = { version = "0.1.0", path = "../crates/config" }

[target.'cfg(linux)'.dependencies]
affinity = "0.1.2"
