[http-server]
host = "127.0.0.1"
port = "9383"
utility-thread-id = 1

[optimizations]
large-pages = true
hard-aes = true
jit = true
secure = false
argon2-sse3 = true
argon2-avx2 = true
argon2 = true
msr = false
threads-per-physical-core = 2

[logs]
report-hashrate = false
log-level = "none"

[state]
state-dir = "../test"
