[package]
name = "ccp-config"
description = "Config for the Fluence CCP application"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = true

[dependencies]
ccp-randomx = { workspace = true }
serde = { workspace = true }
