[rpc-endpoint]
host = "0.0.0.0"
port = "9383"
# Empty list means "all cores"
utility-thread-ids = []

[prometheus-endpoint]
host = "0.0.0.0"
port = "9384"

[optimizations]
# large-pages = true
# hard-aes = true
# jit = true
# secure = false
argon2 = "default" # possible values are: "ssse3", "avx2" or "default"
# msr = false
# threads-per-core = 2

[logs]
report-hashrate = false
log-level = "info"

[state]
# relative path will be resolved relative to Config.toml
# absolute path will work as is
path = "./state"
