name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/artifact.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/artifact.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ccp:
    if: >
      github.event_name == 'push' ||
      (
        contains(github.event.pull_request.labels.*.name, 'e2e') &&
        !github.event.pull_request.head.repo.fork
      )
    uses: ./.github/workflows/artifact.yml
    with:
      ref: ${{ github.ref }}
